server:
  port: 8084
spring:
  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.basedomains.dto
    topic:
      name: order_topics
  datasource:
    url: jdbc:mysql://localhost:3307/orders
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.producer.properties.spring.json.add.type.headers=false
  #spring.datasource.url=jdbc:mysql://localhost:3306/javadevjournal
  #spring.datasource.username=javadevjournal
  #spring.datasource.password=ThePassword
  #spring.jpa.hibernate.ddl-auto=update

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  #spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect